# Site settings
title: Chase Vriezema
email: Chasev825@gmail.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "Keywords, "
skills: "- Software Developer - Game Designer -"
meta_author: Vriezema Chase

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Chase

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c3c3c3 #80B3FF
  primary-rgb: "100,100,100" #"128,179,255"
  secondary: 3f3f3f #FD6E8A
  secondary-dark: 262626 #A2122F

# Footer settings
footer:
  copyright: Chase Vriezema
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: linkedin
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 5122 Lake Creek ct
  - line: Frisco, TX 75035

# Build settings
markdown: kramdown
permalink: pretty
