# Site settings
title: Chase Vriezema
email: Chasev825@gmail.com
url: https://example.github.io
description: "Software Developer and Game Design portfolio for Chase Vriezema. Come look at my projects and learn more about the work that I have done."
keywords: "Keywords, "
skills: "- Software Developer - Game Designer -"
meta_author: Vriezema Chase

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Chase

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c3c3c3 #80B3FF
  primary-rgb: "100,100,100" #"128,179,255"
  secondary: 3f3f3f #FD6E8A
  secondary-dark: 262626 #A2122F

# Footer settings
footer:
  copyright: Chase Vriezema
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SometimesLinds
  - title: linkedin
    url: https://www.linkedin.com/in/chasevriezema825/
  - title: github
    url: https://github.com/chasevriezema

# Build settings
markdown: kramdown
permalink: pretty
